{
  "$$GMExtensionFile": "",
  "%Name":            "${FileName}",
  "constants":        [],
  "copyToTargets":    64,
  "filename":         "${FileName}",
  "final":            "",
  "functions":        ${FileFunctions},
  "init":             "",
  "kind":             1,
  "name":             "",
  "order":            [],
  "origname":         "${FileName}",
  "ProxyFiles":       [],
  "resourceType":     "GMExtensionFile",
  "resourceVersion":  "2.0",
  "uncompress":       false,
  "usesRunnerInterface": false,
}
